### ISSUE TITLE
你好 我搭建你的项目 登录时出现坏的凭证 这是什么原因

### ISSUE THREAD

**Issue by jykSS** [Bai-BaiBai/ns_hospital#1]

**Comment by Bai-BaiBai** [comment]
控制台打印的报错信息`“Encoded password does not look like BCrypt”` -》说明是加密后的密码格式不对，可能是我上传的时候没将admin密码设置为admin导致。
我在dev_update_user分支下的UserServiceImpl下增加了一个main方法，可以调用它查看加密后的密码。验证发现果然是密码和数据库中存储的不一致，至于为什么是报出格式不对而不是`“Authentication failed: password does not match stored value”密码不匹配`我就不知道了。
并且增加了修改密码的功能，现在的密码：
- username : 12345
- bai : baibai
- admin : admin

---

密码加密Bean是在 SecurityConfig类中配置，我使用的是BCryptPasswordEncoder（实现PasswordEncoder接口）。在UserService层注入该Bean，新增用户和修改用户都调用encode方法将加密后的密码存储。

校验逻辑由SpringSecurity框架完成，由于SecurityConfig类被声明成一个配置类，该Bean会被注入到Security中（具体是哪里我不确定，不过点击查看Autowired的地方发现，貌似是ServerHttpSecurityConfiguration这个类中）。在SecurityConfig中的configure方法内，对request进行了拦截，我设置的规则是anyRequest，（后面是我猜的）拦截后如果校验出当前没有用户的登录信息，会进入SecurityService(实现了UserDetailsService)，这里面的loadUserByUsername是进行用户信息查询的，返回的User类实现了UserDetails接口。设置断点Debug发现执行完该方法，拿到User信息后：
`在DaoAuthenticationProvider类中，有以下校验逻辑
this.passwordEncoder.matches(presentedPassword, userDetails.getPassword())`

ps：这个项目是大二的期末小作业，做的比较粗糙，逻辑混乱.....
